from openpack.basepack import DefaultType, OverrideType, Part, Relationship
from openpack.officepack import OfficePackage
from openpack.util import handle
from document import WordDocument
from numbering import NumberingPart
from styles import StylesPart
from headerfooter import HeaderPart, FooterPart

class WordPackage(OfficePackage):
	def __init__(self, name):
		OfficePackage.__init__(self, name)
		if not self._zipfile:
			self.quickstart()

	def quickstart(self):
		self.content_types.add(
			DefaultType(
				"application/xml",
				"xml",
			)
		)
		self.content_types.add(
			DefaultType(
				"application/vnd.openxmlformats-package.relationships+xml",
				"rels",
			)
		)
		start = WordDocument(self, '/word/document.xml')
		self.content_types.add(
			OverrideType(
				start.content_type,
				start.name,
			)
		)
		self[start.name] = start
		self.start_part = start
		self.relate(start)

	@handle(OfficePackage.main_rel)
	def _load_word_doc(self, name, fp):
		self[name] = WordDocument(self, name, fp=fp)

	@handle(StylesPart.rel_type)
	def _load_styles(self, name, fp):
		self[name] = StylesPart(self, name, fp=fp)

	@handle(HeaderPart.rel_type)
	def _load_header(self, name, fp):
		self[name] = HeaderPart(self, name, fp=fp)
	
	@handle(FooterPart.rel_type)
	def _load_footer(self, name, fp):
		self[name] = FooterPart(self, name, fp=fp)

if __name__ == '__main__':
	import sys
	from this import *
	from openpack.basepack import Relationships, CoreProperties, OverrideType
	
	trun = """\
	<w:p>
	  <w:r>
		<w:t>%s</w:t>
	  </w:r>
	</w:p>
"""
	raw_zen = "".join([d.get(c, c) for c in s])
	zen = "".join(trun % line for line in raw_zen.splitlines())
	print raw_zen
	print zen

	body = """\
<?xml version="1.0" encoding="utf-8"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
	<w:p>
	  <w:r><w:t>Generated by:</w:t></w:r>
	</w:p>
	<w:p>
	  <w:r><w:t>Python %s</w:t></w:r>
	</w:p>
%s
  </w:body>
</w:document>
""" % (sys.version, zen)
	op = WordPackage('test.docx')
	op.start_part.fp.write(body.encode('utf-8'))
	op.core_properties = cp = CoreProperties(op, '/docProps/core.xml')
	cp.encoding = 'utf-8'
	op[cp.name] = cp
	op.content_types.add_override(cp)
	op.relate(cp)
	cp.creator = "Testy McTest"
	op.save()

